baseURL = "https://kitty-moments.vercel.app/"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "永远在刮的林中之风"
    signature = "夏日在冰凉的墙壁后面蒸腾、发酵"
    name = "饭桶"